[colors]
## MILITARY UNITS
### AMERICAN
ARMY_GROUP = "#ffb6b6"
CORPS = "#ffb6b6"
FIELD_ARMY = "#ffb6b6"
AIRBORN_DIVISION = "#ffb6b6"
ARMORED_DIVISION = "#ffb6b6"
INFANTRY_DIVISION = "#ffb6b6"
MOUNTAIN_DIVISION = "#ffb6b6"
BATTALION = "#ffb6b6"
CAVALRY = "#ffb6b6"

## EVENTS
### MILITARY
BATTLE = "#ffe9b6"
OPERATION = "#ffe9b6"

## PLACES
### HOLOCAUST
CAMP = "#dcffb6"
GHETTO = "#dcffb6"

## VEHICLES
### AMERICAN
AMPHIBIOUS_VESSEL = "#b6ffe4"
BATTLESHIP = "#b6ffe4"
CARRIER = "#b6ffe4"
CARRIER_ESCORT = "#b6ffe4"
CRUISER = "#b6ffe4"
DESTROYER = "#b6ffe4"
FRIGATE_DESTROYER_ESCORT = "#b6ffe4"
GUNBOAT = "#b6ffe4"
MINE_VESSEL = "#b6ffe4"
PLANE = "#b6ffe4"
SUBMARINE = "#b6ffe4"
TANK = "#b6ffe4"

## WEAPONS
### AMERICAN
ANTI_TANK = "#b6dcff"
BLADE = "#b6dcff"
FLAMETHROWER = "#b6dcff"
GRENADE = "#b6dcff"
MACHINE_GUN = "#b6dcff"
MORTAR = "#b6dcff"
PISTOL = "#b6dcff"
RIFLE = "#b6dcff"
SHOTGUN = "#b6dcff"
SUBMACHINE_GUN = "#b6dcff"

# MISC
MILITARY_PERSONNEL = "#ffb6f8"
