[colors]
AMPHIBIOUS_VESSEL = "#8ac3c2"
ANTI_TANK = "#a87b0c"
ARMORED_DIVISION = "#a87b0c"
BATTALION = "#c6cd98"
BATTLE = "#2c5efd"
BATTLESHIP = "#8ac3c2"
BLADE = "#a87b0c"
CAMP = "#7424ce"
CARRIER = "#8ac3c2"
CARRIER_ESCORT = "#8ac3c2"
CAVALRY = "#c6cd98"
CRUISER = "#8ac3c2"
DESTROYER = "#8ac3c2"
FLAMETHROWER = "#a87b0c"
FRIGATE_DESTROYER_ESCORT = "#8ac3c2"
GHETTO = "#eb2c4f"
GRENADE = "#a87b0c"
GUNBOAT = "#8ac3c2"
INFANTRY_DIVISION = "#c6cd98"
MACHINE_GUN = "#a87b0c"
MILITARY_PERSONNEL = "#8682a3"
MINE_VESSEL = "#8ac3c2"
MORTAR = "#a87b0c"
MOUNTAIN_DIVISION = "#c6cd98"
OPERATION = "#e99341"
PISTOL = "#a87b0c"
PLANE = "#da7662"
RIFLE = "#a87b0c"
SHOTGUN = "#a87b0c"
SUBMACHINE_GUN = "#a87b0c"
SUBMARINE = "#8ac3c2"
TANK = "#3ecc21"
