[colors]
AMPHIBIOUS_VESSEL = "#8ac3c2"
ANTI_TANK = "#e39da2"
ARMORED_DIVISION = "#c6cd98"
BATTALION = "#c6cd98"
BATTLE = "#d6e39d"
BATTLESHIP = "#8ac3c2"
BLADE = "#e39da2"
CAMP = "#7424ce"
CARRIER = "#8ac3c2"
CARRIER_ESCORT = "#8ac3c2"
CAVALRY = "#c6cd98"
CRUISER = "#8ac3c2"
DESTROYER = "#8ac3c2"
FLAMETHROWER = "#e39da2"
FRIGATE_DESTROYER_ESCORT = "#8ac3c2"
GHETTO = "#eb2c4f"
GRENADE = "#e39da2"
GUNBOAT = "#8ac3c2"
INFANTRY_DIVISION = "#c6cd98"
MACHINE_GUN = "#e39da2"
MILITARY_PERSONNEL = "#8682a3"
MINE_VESSEL = "#8ac3c2"
MORTAR = "#a87b0c"
MOUNTAIN_DIVISION = "#c6cd98"
OPERATION = "#e99341"
PISTOL = "#e39da2"
PLANE = "#da7662"
RIFLE = "#e39da2"
SHOTGUN = "#e39da2"
SUBMACHINE_GUN = "#e39da2"
SUBMARINE = "#8ac3c2"
TANK = "#3ecc21"
